-- ══════════════════════════════════════════════════════════════════════════
--  Intelligence Module — Supabase / PostgreSQL schema
--  Run this once in the Supabase SQL Editor.
--
--  Security model (this is what makes the client-side admin safe & $0):
--   • Public / anon key  → may READ only published rows (needs_review = false).
--   • Authenticated admin → may READ everything and UPDATE/DELETE (review).
--   • Pipeline (service key) → bypasses RLS entirely, INSERTs candidates.
--  So the browser never holds a privileged key: RLS does the enforcement.
-- ══════════════════════════════════════════════════════════════════════════

-- ── 1. Processed stories & ingestion log ─────────────────────────────────
CREATE TABLE IF NOT EXISTS public.stories_processed (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id           TEXT UNIQUE NOT NULL,           -- md5(url)
    source             TEXT NOT NULL,
    headline           TEXT NOT NULL,
    url                TEXT NOT NULL,
    score              INT  NOT NULL DEFAULT 0,
    intent_tag         TEXT,
    fingerprint_vector JSONB,                          -- word-frequency map for TF-IDF
    action_taken       TEXT NOT NULL,                  -- scanned | suppressed | alerted | extracted
    processed_at       TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_stories_score_processed
    ON public.stories_processed(score DESC, processed_at DESC);
CREATE INDEX IF NOT EXISTS idx_stories_url ON public.stories_processed(url);

-- ── 2. Enforcement actions (public tracker + review queue) ────────────────
-- `section` values match the 5 tabs in the front-end exactly.
CREATE TABLE IF NOT EXISTS public.enforcement_actions (
    id                 TEXT PRIMARY KEY,               -- e.g. AUTO-2026-0007 / IND-CERT-005
    section            TEXT NOT NULL DEFAULT 'cert_in_breach'
        CHECK (section IN (
            'dpdpa_board', 'sectoral_regulators', 'cert_in_breach',
            'courts_case_law', 'international_benchmarks')),
    date               TEXT NOT NULL,                  -- YYYY-MM-DD
    authority          TEXT NOT NULL,
    company            TEXT NOT NULL,
    sector             TEXT NOT NULL DEFAULT 'Other',
    violation_type     TEXT NOT NULL DEFAULT '',
    dpdpa_section      TEXT NOT NULL DEFAULT '',
    summary            TEXT NOT NULL DEFAULT '',
    penalty_amount     TEXT NOT NULL DEFAULT '',       -- display string, e.g. '₹25 Lakh'
    penalty_amount_inr NUMERIC(15,2) DEFAULT 0,        -- machine-searchable
    outcome            TEXT NOT NULL DEFAULT 'Investigation Ongoing',
    source_url         TEXT UNIQUE,
    notes              TEXT,
    auto_detected      BOOLEAN NOT NULL DEFAULT TRUE,
    needs_review       BOOLEAN NOT NULL DEFAULT TRUE,  -- TRUE = hidden from public
    confidence         TEXT NOT NULL DEFAULT 'medium'
        CHECK (confidence IN ('high', 'medium', 'low')),
    llm_extracted_data JSONB DEFAULT '{}'::jsonb,      -- raw model output + citations
    detected_at        TIMESTAMPTZ DEFAULT NOW(),
    verified_at        TIMESTAMPTZ,
    updated_at         TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_enf_review_date
    ON public.enforcement_actions(needs_review, date DESC);
CREATE INDEX IF NOT EXISTS idx_enf_section ON public.enforcement_actions(section);

-- ── 3. Competitor intelligence ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.competitor_intel (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain          TEXT NOT NULL,
    url             TEXT NOT NULL UNIQUE,
    title           TEXT NOT NULL,
    pub_date        TEXT NOT NULL,
    primary_keyword TEXT,
    word_count      INT DEFAULT 0,
    summary         TEXT,
    gap_flag        BOOLEAN DEFAULT FALSE,
    crawled_at      TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_comp_intel_date
    ON public.competitor_intel(crawled_at DESC);

-- ── 4. Scraper run log (powers the admin "source health" view) ───────────
CREATE TABLE IF NOT EXISTS public.scraper_runs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job         TEXT NOT NULL,          -- enforcement | news_scan | competitor
    source      TEXT,                   -- individual feed/source, nullable for job-level
    status      TEXT NOT NULL,          -- ok | blocked | error
    detail      TEXT,
    items_found INT DEFAULT 0,
    ran_at      TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_scraper_runs_ran ON public.scraper_runs(ran_at DESC);

-- ══════════════════════════════════════════════════════════════════════════
--  Row-Level Security
-- ══════════════════════════════════════════════════════════════════════════
ALTER TABLE public.enforcement_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stories_processed   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competitor_intel    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scraper_runs        ENABLE ROW LEVEL SECURITY;

-- Public may read ONLY verified/published enforcement rows.
DROP POLICY IF EXISTS enf_public_read ON public.enforcement_actions;
CREATE POLICY enf_public_read ON public.enforcement_actions
    FOR SELECT TO anon
    USING (needs_review = false);

-- Signed-in admins may read everything (incl. the review queue).
DROP POLICY IF EXISTS enf_admin_read ON public.enforcement_actions;
CREATE POLICY enf_admin_read ON public.enforcement_actions
    FOR SELECT TO authenticated
    USING (true);

-- Signed-in admins may update rows (verify / edit fields).
DROP POLICY IF EXISTS enf_admin_update ON public.enforcement_actions;
CREATE POLICY enf_admin_update ON public.enforcement_actions
    FOR UPDATE TO authenticated
    USING (true) WITH CHECK (true);

-- Signed-in admins may delete false positives.
DROP POLICY IF EXISTS enf_admin_delete ON public.enforcement_actions;
CREATE POLICY enf_admin_delete ON public.enforcement_actions
    FOR DELETE TO authenticated
    USING (true);

-- Admins can watch the scraper health + intel stream from the dashboard.
DROP POLICY IF EXISTS runs_admin_read ON public.scraper_runs;
CREATE POLICY runs_admin_read ON public.scraper_runs
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS stories_admin_read ON public.stories_processed;
CREATE POLICY stories_admin_read ON public.stories_processed
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS comp_admin_read ON public.competitor_intel;
CREATE POLICY comp_admin_read ON public.competitor_intel
    FOR SELECT TO authenticated USING (true);

-- NOTE: INSERTs come from the pipeline using the service key, which bypasses
-- RLS. No INSERT policy is granted to anon/authenticated on purpose.

-- ── Convenience view: public snapshot (what the static site can query) ────
CREATE OR REPLACE VIEW public.enforcement_public AS
    SELECT id, section, date, authority, company, sector, violation_type,
           dpdpa_section, summary, penalty_amount, penalty_amount_inr,
           outcome, source_url, updated_at
    FROM public.enforcement_actions
    WHERE needs_review = false
    ORDER BY date DESC;

GRANT SELECT ON public.enforcement_public TO anon, authenticated;

-- ══════════════════════════════════════════════════════════════════════════
--  Intelligence upgrades (items 1-4, 6-9)
-- ══════════════════════════════════════════════════════════════════════════

-- Clustering (#2): corroborating sources; Grounding (#3): official source;
-- Re-verification (#7): when we last re-checked an open case.
ALTER TABLE public.enforcement_actions
    ADD COLUMN IF NOT EXISTS sources JSONB DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS official_source_url TEXT,
    ADD COLUMN IF NOT EXISTS last_reverified_at TIMESTAMPTZ;

-- Feedback loop (#4): every reviewer verify/discard becomes training signal.
CREATE TABLE IF NOT EXISTS public.review_decisions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_id   TEXT,
    decision    TEXT NOT NULL CHECK (decision IN ('verified', 'discarded')),
    title       TEXT,
    snippet     TEXT,
    source_url  TEXT,
    signature   TEXT,                 -- normalised company|authority for FP memory
    fields      JSONB DEFAULT '{}'::jsonb,
    decided_at  TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_decisions_decided ON public.review_decisions(decided_at DESC);
CREATE INDEX IF NOT EXISTS idx_decisions_sig ON public.review_decisions(signature);

-- Weekly executive brief (#6).
CREATE TABLE IF NOT EXISTS public.intel_briefs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period      TEXT NOT NULL,         -- e.g. 2026-W38
    markdown    TEXT NOT NULL,
    stats       JSONB DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_briefs_period ON public.intel_briefs(period);

-- Story -> content angle (#9).
CREATE TABLE IF NOT EXISTS public.content_angles (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_url     TEXT UNIQUE,
    headline      TEXT,
    angle         TEXT NOT NULL,
    target_keyword TEXT,
    rationale     TEXT,
    score         INT DEFAULT 0,
    created_at    TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_angles_created ON public.content_angles(created_at DESC);

ALTER TABLE public.review_decisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.intel_briefs     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_angles   ENABLE ROW LEVEL SECURITY;

-- Reviewers may log decisions and read the intelligence outputs.
DROP POLICY IF EXISTS dec_admin_all ON public.review_decisions;
CREATE POLICY dec_admin_all ON public.review_decisions
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS briefs_admin_read ON public.intel_briefs;
CREATE POLICY briefs_admin_read ON public.intel_briefs
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS angles_admin_read ON public.content_angles;
CREATE POLICY angles_admin_read ON public.content_angles
    FOR SELECT TO authenticated USING (true);

-- The weekly brief is safe to expose publicly (aggregate, no PII).
DROP POLICY IF EXISTS briefs_public_read ON public.intel_briefs;
CREATE POLICY briefs_public_read ON public.intel_briefs
    FOR SELECT TO anon USING (true);
-- Pipeline writes to briefs/angles/decisions use the service key (bypasses RLS).
